src/bundler.js
src/defaultBrowserPackOptions.json
src/defaultOptions.json
src/index.js

https://github.com/MiguelCastillo/bit-bundler/issues/6

Fixed issue with standaloneModule not properly handling file path ids

---

src/bundler.js

https://github.com/MiguelCastillo/bit-bundler/issues/12

Fixed regression with `bundl` not found

---

plugins/vendor/index.js
src/bundler.js

https://github.com/MiguelCastillo/bit-bundler/issues/21

Changes to run bundler plugins first and then the main bundler.

---

bundlers/browserpack/index.js

https://github.com/MiguelCastillo/bit-bundler/issues/24

Tweak logic for browserpack bundler to gracefully handle no options

---

src/loader.js

https://github.com/MiguelCastillo/bit-bundler/issues/26

Fixed path for bit-bundler-utils

---

Gruntfile.js
package.json
tasks/concurrent.js
tasks/connect.js
tasks/eslint.js
tasks/mocha.js
tasks/release.js
tasks/uglify.js
tasks/watch.js

https://github.com/MiguelCastillo/bit-bundler/issues/32

Modularized gruntfile.js

---

src/bundler.js
src/context.js
src/loader.js

https://github.com/MiguelCastillo/bit-bundler/issues/35

Fixed lint warnings

---

bower.json

https://github.com/MiguelCastillo/bit-bundler/issues/38

Removed bower config

---

src/bundler.js
src/loader.js

https://github.com/MiguelCastillo/bit-bundler/issues/43

Fix 43 rename to provider

---

package.json
src/bundler.js
src/fileReader.js

https://github.com/MiguelCastillo/bit-bundler/issues/45

Added bit-bundler-browserpack as the default bundler provider

---

.gitignore
test/spec/index.js

Tweaked tests to generate test bundles in the test directory and also added that to the gitignore list so that they do not get committed.

Ignore test dest

---

examples/README.md

Fixed elasticsearch links in example's README

---

package.json

chore(package): update belty to version 5.0.3

---

package.json
src/bundle.js
src/context.js
src/index.js
src/watch.js
test/spec/index.js

This is to set us up for allowing livereload and multi process bundling

Bitbundler context splitup

---

loggers/buildstats.js

the issues are around piped streams not properly getting messages written to them.  Also changed the buildstatus to only report warnings and errors

fixed issues with streaming in the buildstatus logger

---

loggers/buildstats.js
src/bundleWriter.js
src/context.js
src/index.js

- added logger interface in Bitbundler
- refactored bundle writer to use bundleVisitor instead of manual traversal

Bundler logger interface

---

loggers/buildstats.js
src/bundleWriter.js
src/context.js
src/index.js
test/spec/index.js

- Moved buildwriter to bitbundler API level.
- consolidated some of the build messages.

Buildwriter refactor

---

examples/splitter/.bitbundler.js
src/bundle.js
src/bundleWriter.js
src/context.js
src/index.js

** BREAKING CHANGE **
Removed misc arguments pass to visitor functions when visiting bundles

Bundle dest cleanup

---

package.json

fix(package): update bit-bundler-browserpack to version 4.0.1

---

src/bundleWriter.js
src/bundler.js
src/context.js
src/index.js
src/loader.js

all things classes and lambdas where appropriate.
/cc @jrwren

Es2015 migration

---

examples/webapp/.babelrc
examples/webapp/.bitbundler.js
examples/webapp/.eslintrc.json
examples/webapp/package.json
examples/webapp/src/hello.js
examples/webapp/src/index.html
examples/webapp/src/main.js

in this PR we are adding
- babelrc to configure es2015 and react transpiling.
- eslint for static analysis of our code
- react!!  well - to render react components.

Webapp extended setup

---

bin/cli.js
docs/api/Bitbundler.md
docs/api/bundle.md
docs/cli/Options.md
examples/from-contents/.bitbundler.js
package.json
src/index.js
src/loader/pool.js
test/spec/index.js

Also - updated dependencies to make sure we have the proper contents to content rename across modules and dependencies

Contents to content

---

src/bundle/app-bundle-prelude.js

this PR is to fix https://github.com/MiguelCastillo/bit-bundler/issues/350, which exposes issues with split bundles not executing correctly due to circular dependencies that span separate bundles.

added logic to handle circular references across bundles

---

src/index.js
src/loader/pool.js
test/spec/index.js

This PR allows us to do things like 
``` javascript
bundle([{ content: "console.log('hello world');" }, { name: "util" }, "src/*.js"])
```

introducing processing of multiple files/content items

---

src/bundler/chunkedBundle.js
src/bundler/chunkedBundleBuilder.js
test/spec/index.js

some of the refactoring is to make the code more streamlined in terms of who prepares the modules to be bundled. some module preparation would take place in the chunckedBundleBuilder and some would take place in chunkedBundle. All module preparation has been moved to chunkedBundle.

refactored chunk bundle to make the code a bit more streamlined

---

docs/BundlerPlugins.md
docs/HelloWorld.md
docs/Installation.md
docs/LoaderPlugins.md
docs/api/Bitbundler.md
docs/api/bundle.md
docs/cli/Examples.md

Here we are just changing import references to use bit npm . Aka `@bit/`

Updated docs to point to bit npm org. Step 3

---

src/context.js
test/SpecRunner.js
test/spec/context.js

Adding unit tests for Context as well as a few syntax tweaks for better readability.
To test:
```
$ npm run test
```

Adding unit tests for Context

---

src/bundle/index.js
test/SpecRunner.js
test/spec/bundle/bundle.js

Adding Bundle tests and made changes to make Bundle immutable.

Adding Bundle tests
